### PR TITLE
Add basic tests

### PR DESCRIPTION
**Pull request by iliebabcenco**
In this pull request I achieved the next goals:

1. Add tests for all functionality of the calculate.js;
2. Add snapshot tests for Home, Quote, Calculator components;
3. Add tests for operate.js.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑️🛑️🛑️🛑️**

Hello @iliebabcenco 
Great work on this milestone. I like how thorough the tests are.
However, let's make few changes and get the milestone approved.

[REQUIRED]: Choose between yarn or npm as it is causing conflicts having both yarn.lock and package.lock.
[REQUIRED]: Add negative test cases in other test files as well.

That's it

Make the required changes and ask for another review👍️👍️

Happy coding 💻️💻️💻️💻️

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello, @iliebabcenco  👋🏾 👋🏾 congratulations on making it this far 😄 . 

#### Highlights

- You have worked on the feedback given by the previous TSE ✔️ 

#### To improve
 
- [ ] Whenever I try to run `npm test` to check if your tests pass or fail I get the following error ⬇️ As a developer your project should be able to run across all devices seamlessly. Kindly fix this
image



That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

**Comment by iliebabcenco** [comment]
Hey, 
I want to mention that your error is local, as you can read in the screenshot.
You will meet this issue with every new react project on your machine.
So in order to fix it, you have to create a .env document and put in it:
`SKIP_PREFLIGHT_CHECK=true`

**Comment by rukundoeric** [comment]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 
  - All test are passing. 💯 

- ### To Improve
  - N/A

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/),
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
